# Basic Information 
title: Zoltán Szatmáry
position: M.Sc. Student
affiliation: Budapest University of Technology and Economics
affiliation_link: https://www.bme.hu/en
email: szatmary.zoltan@outlook.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Szatmáry Zoltán BME
description: Second-year Master's student in Computer Science Engineering at the Budapest University of Technology and Economics (BME).
canonical: https://zoltanszatmary.com/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=amIDvmAAAAAJ
cv_link: assets/files/cv.pdf
github_link: https://github.com/zoltanszatmary
linkedin: https://www.linkedin.com/in/zoltan-szatmary/
twitter: https://x.com/ZoltanSzatmary

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light
